require 'dashbozu/plugin'
require 'dashbozu/output'
require 'dashbozu/output_asakusa_satellite'
require 'dashbozu/output_chat_work'
require 'dashbozu/output_http'
require 'dashbozu/input'
require 'dashbozu/input_bitbucket'
require 'dashbozu/input_jenkins'
require 'dashbozu/input_errbit'
require 'dashbozu/input_github'
require 'dashbozu/input_new_relic'
require 'dashbozu/input_sunline'
require 'dashbozu/input_travis_ci'
require 'dashbozu/input_heroku'
require 'dashbozu/input_wercker'
require 'dashbozu/input_redmine'

